gourmet_guide/urls.py
from django.urls import path
from . import views
app_name = 'gourmet_guide'
urlpatterns = [
    path('', views.IndexViews.as_view(), name='index'),
    path('<int:pk>',views.DetailView.as_view(),name="detail"),
    path('create/', views.CreateView.as_view(), name="create"),
    path('<int:pk>/update', views.UpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name="delete")
]

gourmet_guide/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
#<category>
#カテゴリモデル:飲食店のカテゴリ（例：フレンチ、イタリアン、寿司など）を表現。
class Category(models.Model):
    name = models.CharField(max_length=255)#カテゴリの名前を書くのする文字フィールド（例：フレンチ）
    author = models.ForeignKey(#　カテゴリを作成したユーザーのリレーションシップを表現
        'auth.User',  # Djangoのデフォルトのユーザーモデルを指定
        on_delete=models.CASCADE,  # ユーザーが削除された場合、関連するカテゴリも削除
    )
    created_at = models.DateTimeField(auto_now_add=True)#カテゴリの作成日時を格納する日時フィールド。（自動追加）
    updated_at = models.DateTimeField(auto_now=True)#カテゴリの更新日時を格納する日時フィールド。（自動更新）
    def __str__(self):
        return self.name# カテゴリの名前を文字列として返す。（管理者画面などで表示される）
    
#<shop>
#店舗モデル:飲食店の情報を表現
class Shop(models.Model):
    name = models.CharField(max_length=255)# 飲食店の名前を格納する文字列フィールド
    address = models.CharField(max_length=255)# 飲食店の住所を書くの巣うる文字列フィールド
    author = models.ForeignKey(# 飲食店を作成したユーザーとのリレーションシップを表現
        'auth.User',  # Djangoのデフォルトのユーザーモデルを指定
        on_delete=models.CASCADE,# ユーザーが削除された場合、関連する店舗も削除。
    )
    category = models.ForeignKey(# 飲食店のカテゴリとのリレーションシップを表現
        Category,# カテゴリモデルとのリレーションシップ
        on_delete=models.PROTECT,# 関連するカテゴリが削除されても削除されない。
    )
    created_at = models.DateTimeField(auto_now_add=True)# 飲食店の作成日時を格納する日時フィールド（自動追加）
    updated_at = models.DateTimeField(auto_now=True)# 飲食店の更新日時を格納する日時フィールド（自動更新）
    def __str__(self):
        return self.name# 飲食店の名前を文字列として返す（管理画面などで表示される。）
    
    def get_absolute_url(self):
        return reverse('gourmet_guide:detail', kwargs={'pk': self.pk})

gourmet_guide/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
import requests
import urllib
from django.views import generic#便利なテンプレート機能を使えるようにする
from .models import Category,Shop

class DetailView(generic.DetailView):
    # ↓ 使用するテンプレートファイルを指定
    template_name = 'gourmet_guide/wonderful_shop_detail.html'
    model = Shop
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        shop_instance = self.get_object()
        address = shop_instance.address
        makeUrl = "https://msearch.gsi.go.jp/address-search/AddressSearch?q="
        s_quote = urllib.parse.quote(address)
        response = requests.get(makeUrl + s_quote)
        print("response", response)
        coordinates = response.json()[0]["geometry"]["coordinates"]
        print("coordinates", coordinates)
        reversed_coordinates = reversed(coordinates)
        context['coordinates'] = ",".join(map(str, reversed_coordinates))
        print("context['coordinates']", context['coordinates'])
        return context


    





class IndexViews(generic.ListView):#データが一覧表示されるようにする
    model = Shop#どのモデルを一覧表示するか
class CreateView(generic.edit.CreateView):
    model = Shop
    fields = "__all__"
class UpdateView(generic.edit.UpdateView):
    model = Shop
    fields = "__all__"

class DeleteView(generic.edit.DeleteView):
    model = Shop
    # reverse_lazyの引数に表示したいページのnameを指定
    success_url = reverse_lazy('gourmet_guide:index')

gourmet_guide/templates/gourmet_guide/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shop list</title>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' >
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-dark fixed-top">
  <div class="container">
      <a class='navbar-brand' href='{% url "gourmet_guide:index" %}'>おすすめご飯やさん&trade;</a>
    </div>
  </nav>
  <div class="container">
  {% block content %}

  {% endblock %}
  </div>
</body>
</html>

gourmet_guide/templates/gourmet_guide/shop_confirm_delete.html
<h1>お店情報の削除</h1>
<p>「{{ object.name }}」を削除しますか？</p>
<form action="" method="POST">
  {% csrf_token %}
  <button type="submit" class="submit delete">削除</button>
</form>

gourmet_guide/templates/gourmet_guide/shop_form.html
{% extends './base.html' %}
{% block content %}
<h1>お店情報の{{ object|yesno:'更新,作成' }}</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="submit">
    {{ object|yesno:'更新,作成' }}
  </button>
</form>
<div>
  <a href="Javascript:history.back()">&lt; 戻る</a>
  <!-- &ltは特殊文字で、htmlタグと区別するときに使われる。 -->
</div>
{% endblock %}

gourmet_guide/templates/gourmet_guide/shop_list.html
{% extends './base.html' %} 
{% block content %}
  <h1>お店一覧</h1>
  <div>
    <a href="{% url 'gourmet_guide:create' %}">新規登録</a>
  </div>
  <table class="table table-striped table-hover">
    <tr>
      <th>店名</th>
      <th>カテゴリー</th>
      <th>住所</th>
    </tr>
    {% for shop in object_list %}
    <tr>
       <td><a href="{% url 'gourmet_guide:detail' shop.pk %}">{{ shop.name }}</a></td>
      <td>{{ shop.category.name }}</td>
      <td>{{ shop.address }}</td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

gourmet_guide/templates/gourmet_guide/wonderful_shop_detail.html
{% block content %}
<h1>{{ shop.name }}</h1>
<div>
  <p>{{ shop.category.name }}</p>
  <p>{{ shop.address }}</p>
  <iframe src='https://maps.google.co.jp/maps?output=embed&q={{coordinates}}&z=16' allowfullscreen="" width="1000px" height="300px"></iframe>
</div>
<div>
  <a href="{% url 'gourmet_guide:index' %}">一覧ページへ</a>
  <a href="{% url 'gourmet_guide:update' shop.pk %}">編集</a>
  <a href="{% url 'gourmet_guide:delete' shop.pk %}">削除</a>
</div>
{% endblock %}